---

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr == 'systemd'

- name: reload certbot
  listen: reload certbot.timer
  ansible.builtin.service:
    name: "{{ certbot_systemd.service_name.timer | default('certbot.timer') }}"
    state: reloaded
  when:
    - ansible_service_mgr == 'systemd'
    - certbot_systemd.use_timer

- name: restart certbot
  listen: restart certbot.timer
  ansible.builtin.service:
    name: "{{ certbot_systemd.service_name.timer | default('certbot.timer') }}"
    state: restarted
  when:
    - ansible_service_mgr == 'systemd'
    - certbot_systemd.use_timer

...
