---

certbot_config:
  conf_directory: /etc/letsencrypt
  www_directory: /var/www/certbot
  well_known_directory: /var/www/certbot/.well-known/acme-challenge
  rsa_key_size: 4096
  email: pki@test.com
  expire_days_limit: 20

certbot_tls_certificates: []
#  - domain: foo.bar
#    subdomains: www.foo.bar
#  - domain: foo-foo.bar
#    subdomains:
#      - www.foo-foo.bar
#      - assets.foo-foo.bar

certbot_notification:
  enabled: false
  smtp:
    server_name: localhost      # smtp.example.com
    port: 25                    # 587
    auth:
      username: ""              #
      password: ""              #
  sender: ""                    # backup@example.com
  recipient: ""                 # admin@foo.bar

certbot_test_cert: true
certbot_dry_run: true
certbot_auto_expand: false

certbot_systemd: {}
#  use_timer: true
#  service_name:
#    timer: certbot.timer
#    service: certbot.service

certbot_staging_args: []
#  - --test-cert
#  - --dry-run

certbot_restart_services: []
#  - service: nginx


certbot_cron:
  type: systemd       # alternative: cron
  daemon: ""          # "{{ 'cron' if ansible_os_family | lower == 'debian' else 'cronie' }}"
  enabled: true       # [true, false]
  minute: "58"        # 58
  hour: "2"           # 2
  weekday: "Mon"      # *

...
