---

certbot_requirements:
  # - iproute2
  # - bc
  # - python-jinja
  - python-dnspython
  - python-dbus
  - python-ansi2html

certbot_system:
  user: http
  group: http

certbot_defaults_systemd:
  use_timer: true
  service_name:
    timer: certbot-renew.timer
    service: certbot-renew.service

...
