---

pki_cert_dir: /etc/ssl/certs
pki_key_dir: /etc/ssl/private

_step_ca_key_exists: false
_step_ca_missing_cert: true

step_ca_defaults_directory: /etc/default

systemd_lib_directory: /lib/systemd/system

...
