---

- name: add smallstep apt sources
  when:
    - ansible_facts.os_family | lower == 'debian'
  bodsch.core.apt_sources:
    name: smallstep-latest
    filename: smallstep-latest.sources
    uris:
      - https://packages.smallstep.com/stable/debian
    suites: debs
    components:
      - main
    signed_by: /etc/apt/trusted.gpg.d/smallstep.asc
    key:
      method: download
      url: https://packages.smallstep.com/keys/apt/repo-signing-key.gpg
      dest: /etc/apt/trusted.gpg.d/smallstep.asc
      dearmor: true
      validate: true
    update_cache: true

...
