---

galaxy_info:
  role_name: python_pip_modules
  namespace: amedes

  author: Bodo Schulz
  description: installs various pip modules.

  license: "MIT"
  min_ansible_version: "2.11"

  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - system
    - proxy

dependencies: []

...
