---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        # artixlinux-openrc
        - "{{ ansible_distribution | lower | replace(' ', '') }}-{{ ansible_service_mgr | lower }}.yml"
        - default.yml
      skip: true

- name: detect ansible check_mode
  bodsch.core.check_mode:
  register: _check_mode

- name: define running_in_check_mode
  ansible.builtin.set_fact:
    running_in_check_mode: '{{ _check_mode.check_mode }}'

# - name: d
#   debug:
#     msg:
#       - "{{ step_ca_init_password }}"
#       - "{{ step_ca_init_password | default('') | length == 0 }}"

- name: validate init password
  when:
    - step_ca_init_password | default('') | length == 0
  block:
    - name: warn if a init password is not specified
      ansible.builtin.fail:
        msg: |
          - WARNING -
          The CA init password was left empty.
          Please set a custom password with role variable 'step_ca_init_password'
          to secure your CA!
      ignore_errors: true

    - name: wait 10 seconds to realise the message
      delegate_to: localhost
      ansible.builtin.wait_for:
        timeout: 10

    - name: full stop at errors
      ansible.builtin.meta: end_play

- name: install dependencies
  ansible.builtin.package:
    name: "{{ step_ca_dependencies }}"
    state: present
  when:
    - step_ca_dependencies | default([]) | count > 0

...
