---

- name: define full domain list
  ansible.builtin.set_fact:
    certbot_full_domain_list: "{{ certbot_tls_certificates | domain_list(item) | join(' --domain ') }}"

- name: create certificate with certbot certonly
  ansible.builtin.shell: |
    certbot certonly \
      {{ certbot_staging_args | join(' ') }} \
      --webroot \
      --webroot-path {{ certbot_config.www_directory }} \
      --rsa-key-size {{ certbot_config.rsa_key_size }} \
      --domain {{ certbot_full_domain_list }} \
      --cert-path {{ certbot_config.conf_directory }}/live/{{ item }} \
      --non-interactive \
      --agree-tos \
      --expand \
      --email {{ certbot_config.email }}
  register: _certbot_certonly
  when:
    - certbot_full_domain_list is defined
    - certbot_full_domain_list | string | length > 0
    - not certbot_dry_run | default('true')

...
