---

- name: detect if certbot installed
  ansible.builtin.stat:
    path: /usr/bin/certbot
    get_checksum: false
    get_mime: false
  register: certbot_binary_file

- name: define certbot_installed if certbot installed
  ansible.builtin.set_fact:
    certbot_installed: "{{ certbot_binary_file.stat.exists }}"
  when:
    - certbot_binary_file is defined
    - certbot_binary_file.stat is defined

- name: create policy-rc.d
  ansible.builtin.copy:
    dest: /usr/sbin/policy-rc.d
    content: |
      #!/bin/sh
      exit 101
    mode: "0755"
  when:
    - not certbot_installed
    - ansible_facts.os_family | lower != 'archlinux'

- name: install requirements
  ansible.builtin.package:
    name: "{{ certbot_requirements }}"
    state: present
  when:
    - certbot_requirements | default([]) | count > 0

- name: install certbot
  ansible.builtin.package:
    name: certbot
    state: present

- name: remove policy-rc.d
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  when:
    - ansible_facts.os_family | lower != 'archlinux'

...
