---

- name: create policy-rc.d
  ansible.builtin.copy:
    dest: /usr/sbin/policy-rc.d
    content: |
      #!/bin/sh
      exit 101
    mode: "0755"
  when:
    - not certbot_installed
    - ansible_os_family | lower != 'archlinux'

- name: install requirements
  ansible.builtin.package:
    name: "{{ certbot_requirements }}"
    state: present
  when:
    - certbot_requirements | default([]) | count > 0

- name: install certbot
  ansible.builtin.package:
    name: certbot
    state: present

- name: remove policy-rc.d
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  when:
    - ansible_os_family | lower != 'archlinux'

- name: disable original systemd units
  when:
    - ansible_service_mgr == 'systemd'
  block:
    - name: disable original certbot.service
      ansible.builtin.service:
        name: certbot.service
        enabled: false
      failed_when: false

    - name: disable original certbot.timer
      ansible.builtin.service:
        name: certbot.timer
        enabled: false
      failed_when: false

...
