---

- name: define download information
  ansible.builtin.set_fact:
    lego_release: "{{ lego_defaults_release | combine(lego_release, recursive=True) }}"

- name: resolve lego release
  when:
    - not running_in_check_mode
  become: false
  delegate_to: localhost
  run_once: true
  bodsch.scm.scm_release:
    provider: "github"
    project: go-acme
    repository: lego
    version: "{{ lego_version }}" # "latest" | "2.53.0" | "v2.53.0"
    architecture: "{{ ansible_facts.architecture }}"
    system: "{{ ansible_facts.system }}"
    user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
    password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
  register: _release

- name: re-define lego_version
  when:
    - not running_in_check_mode
    - lego_version == "latest"
    - _release.version is defined
    - _release.version | length > 0
  ansible.builtin.set_fact:
    lego_version: "{{ _release.version }}"

- name: detect the downloaded lego archive
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ lego_local_tmp_directory }}/{{ lego_release.file }}"
  register: lego_stat_archive

- name: define delegate instance for download handling
  when:
    - not running_in_check_mode
    - lego_direct_download
  ansible.builtin.set_fact:
    lego_delegate_to: "{{ ansible_facts.host }}"
    lego_local_tmp_directory: "{{
      lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
      default('/var/cache/ansible/lego', true) }}/{{ lego_version }}"

- name: create download directory
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ lego_local_tmp_directory }}"
    state: directory
    mode: "0750"
  check_mode: false

- name: detect the downloaded lego archive
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ lego_local_tmp_directory }}/{{ _release.file }}"
  register: stat_lego_archive

- name: download
  when:
    - not running_in_check_mode
    - lego_stat_archive.stat is defined
    - not lego_stat_archive.stat.exists | default('false')
  block:

    - name: download lego binary archive
      become: false
      delegate_to: "{{ lego_delegate_to }}"
      run_once: "{{ 'false' if lego_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ _release.download_url }}"
        url_username: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        url_password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
        dest: "{{ lego_local_tmp_directory }}/{{ _release.file }}"
        checksum: "{{ _release.checksum_string | default(omit) }}"
        mode: "0640"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ lego_delegate_to }}"
      run_once: "{{ 'false' if lego_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ lego_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect downloaded file
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ lego_local_tmp_directory }}/{{ lego_release.file }}"
  register: lego_stat_archive

- name: detect extracted binary
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ lego_local_tmp_directory }}/{{ lego_release.binary }}"
  register: lego_stat_binary

- name: extract lego archive
  when:
    - not running_in_check_mode
    - lego_stat_archive.stat is defined
    - lego_stat_archive.stat.exists | default('false') | bool
    - lego_stat_archive.stat.mimetype in ["application/zip","application/gzip"]
    - lego_stat_binary.stat is defined
    - not lego_stat_binary.stat.exists | default('false') | bool
  become: false
  delegate_to: "{{ lego_delegate_to }}"
  run_once: "{{ 'false' if lego_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ lego_local_tmp_directory }}/{{ _release.file }}"
    dest: "{{ lego_local_tmp_directory }}/"
    # copy: false
    remote_src: "{{ 'true' if lego_direct_download else 'false' }}"

...
