---

- name: user and group handling
  when:
    - lego_system_user != "root"
  block:
    - name: create lego group
      ansible.builtin.group:
        name: "{{ lego_system_group }}"
        state: present
        system: true

    - name: create lego user
      ansible.builtin.user:
        name: "{{ lego_system_user }}"
        groups: "{{ lego_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ lego_install_path }}"
    state: directory
    owner: "{{ lego_system_user }}"
    group: "{{ lego_system_group }}"
    mode: "0755"

- name: deploy and activate lego version {{ lego_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ lego_local_tmp_directory }}"
    install_dir: "{{ lego_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if lego_direct_download else 'false') | bool }}"
    owner: "{{ lego_system_user }}"
    group: "{{ lego_system_group }}"
    mode: "0755"
    items:
      - name: "{{ lego_release.binary }}"
        capability: "cap_net_raw+ep"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: lego
    facts:
      version: "{{ lego_version }}"

...
