---

step_ca_domain: domain.local

step_ca_packages:
  - step-cli
  - step-ca

step_ca_system:
  owner: step-ca
  group: step-ca
  home: /opt/step-ca

step_ca_service:
  state: started
  enabled: true

step_ca_force: false

step_ca_support_acme: false

# e.g. 'cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1'
step_ca_init_password: ""


step_ca_authority:
  name: ""
  dns: []
  provisioners: []
  config:
    tls_duration:
      default: 48h
      min: 5m
      max: 168h
    ssh_durations:
      host:
        default: 48h
        min: 5m
        max: 168h
      user:
        default: 48h
        min: 5m
        max: 168h
    disable_renewal: false
    allow_renewal_after_expiry: false

# #step_ca_force_create:
# step_ca_force_certify_nodes: false
# # see "{{ ansible_os_family }}.yml"
# step_ca_defult_ssl_certs_dir: "{{ pki_cert_dir | default('/etc/ssl/certs') }}"
# step_ca_defult_ssl_key_dir: "{{ pki_key_dir | default('/etc/ssl/private') }}"
#
# # how long should remain before we generate a new CA cert ?
# step_ca_cert_expiration_panic_threshold: 604800 # 1 week
#
# # where to generate the certs
# step_ca_certs_dir: /usr/share/ca-certs
#
# # where to copy the produces files to
# step_ca_distribution_certs_dir: "{{ playbook_dir }}/../keys_n_certs"
#
# step_ca_rootstep_ca_password: Chang3m3
# step_ca_cert: ca.pem
# step_ca_key: ca-priv-key.pem
#
# step_ca_dn:
#   country: DE
#   state: Hamburg
#   location: Hamburg
#   organisation: ACME Inc.
#   organisational_unit: "BOfH"
#   domain: "{{ step_ca_domain }}"
#   commonname: "{{ step_ca_domain }}"
#   email: "cert@{{ step_ca_domain }}"

...
