---

# - name: detect installed python version
#   set_fact:
#     _python_version: "{{ ansible_python.version.major }}"
#     python_pip_requirements: /tmp/pip-requirements_{{ _python_version }}.txt
#
# - name: detect python binary
#   stat:
#     path: "/usr/bin/python{{ use_python_version }}"
#   register: python_binary

- name: create requirements.txt
  ansible.builtin.template:
    src: pip-requirements.txt.j2
    dest: "{{ python_pip_requirements }}"
    mode: 0660

...
