---

name: remove old workflows

on:
  workflow_dispatch:

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-20.04
    name: delete workflow runs

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: delete workflow runs
        uses: MajorScruffy/delete-workflow-runs
        id: delete-workflow-runs
        with:
          repository: MajorScruffy/delete-workflow-runs   # replace this with your own repository
          # older-than-seconds: 86400                       # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


