---
name: redhat-based

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-jenkins'

jobs:
  rpm:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }}"
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - oraclelinux:8
          - rockylinux:8
          - almalinux:8
          #
          - oraclelinux:9
          - rockylinux:9
          - almalinux:9
        python-version:
          - '3.9'
        ansible-version:
          - '5.1'
          - '6.7'
        scenario:
          - redhat-based
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-jenkins'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: test default
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
